model_name: "MNN"
project_filepath: "/raid/KAICD_sarscov2/"
save_filepath: "ChemGG/checkpoint/"
params_filepath: "Config/ChemGG.json"
train_hdf_filepath: "data/pretraining/ChemGG/train.h5"
valid_hdf_filepath: "data/pretraining/ChemGG/valid.h5"
test_hdf_filepath: "data/pretraining/ChemGG/test.h5"
