model_name: "ChemVAE_5M"
project_filepath: "/raid/KAICD_sarscov2/"
save_filepath: "ChemVAE/checkpoint/"
smiles_language_filepath: "Config/selfies_language.pkl"
params_filepath: "Config/ChemVAE.json"
train_smiles_filepath: "data/pretraining/ChemVAE/train_final_seed.smi"
test_smiles_filepath: "data/pretraining/ChemVAE/test_final_seed.smi"
train_dataset_filepath: "preprocessing/ChemVAE_train_dataset_final.pkl"
test_dataset_filepath: "preprocessing/ChemVAE_test_dataset_final.pkl"
checkpoint_filepath: "ChemVAE/checkpoint/ChemVAE_5M.ckpt"
