wandb:
  entity: "kaicd"
  project: "PaccMann_sarscov2_Pipeline_Test"

model: "Toxicity"

DTI_filepath:
  project_filepath: "/raid/PaccMann_sarscov2/"
  save_filepath: "/raid/PaccMann_sarscov2/paccmann_predictor/checkpoint/"
  smiles_language_filepath: "data/pretraining/language_models/smiles_language_chembl_gdsc_ccle_tox21_zinc_organdb_bindingdb.pkl"
  protein_language_filepath: "data/pretraining/language_models/protein_language_bindingdb.pkl"
  params_filepath: "Config/affinity.json"
  train_affinity_filepath: "data/pretraining/affinity_predictor/filtered_train_binding_data.csv"
  test_affinity_filepath: "data/pretraining/affinity_predictor/filtered_val_binding_data.csv"
  protein_filepath: "data/pretraining/affinity_predictor/sequences.smi"
  smi_filepath: "data/pretraining/affinity_predictor/filtered_ligands.smi"

Toxicity_filepath:
  project_filepath: "/raid/PaccMann_sarscov2/"
  save_filepath: "/raid/PaccMann_sarscov2/paccmann_toxsmi/checkpoint/"
  params_filepath: "Config/affinity.json"
  embedding_path: "data/pretraining/toxicity_predictor/smiles_vae_embeddings.pkl"
  train_score_filepath: "data/pretraining/toxicity_predictor/tox21_train.csv"
  test_score_filepath: "data/pretraining/toxicity_predictor/tox21_test.csv"
  smi_filepath: "data/pretraining/toxicity_predictor/tox21.smi"
  smiles_language_filepath: "data/pretraining/language_models/smiles_language_tox21.pkl"

ChemVAE_filepath:
  project_filepath: "/raid/PaccMann_sarscov2/"
  save_filepath: "/raid/PaccMann_sarscov2/paccmann_chemistry/checkpoint/"
  smiles_language_filepath: "data/pretraining/language_models/selfies_language.pkl"
  params_filepath: "Config/selfies.json"
  train_affinity_filepath: "data/pretraining/SELFIESVAE/train_chembl_22_clean_1576904_sorted_std_final.smi"
  test_affinity_filepath: "data/pretraining/SELFIESVAE/test_chembl_22_clean_1576904_sorted_std_final.smi"

ProtVAE_filepath:
  project_filepath: "/raid/PaccMann_sarscov2/"
  save_filepath: "/raid/PaccMann_sarscov2/paccmann_omics/checkpoint/"
  params_filepath: "Config/omics.json"
  train_filepath: "data/pretraining/ProteinVAE/tape_encoded/train_representation.csv"
  test_filepath: "data/pretraining/ProteinVAE/tape_encoded/val_representation.csv"

Reinforce_filepath:
  mol_model_path: "/raid/paccmann-covid/models/SELFIESVAE"
  protein_model_path: "/raid/paccmann-covid/models/ProteinVAE"
  affinity_model_path: "/raid/paccmann-covid/models/affinity"
  protein_data_path: "/raid/paccmann-covid/data/training/merged_sequence_encoding/uniprot_covid-19.csv"
  params_path: "Config/conditional_generator.json"
  model_name: "paccmann_sarscov2"
  test_protein_id: 35
  unbiased_predictions_path: "/raid/paccmann-covid/data/training/unbiased_predictions"
  tox21_path: "/raid/paccmann-covid/models/Tox21"
  organdb_path:
  site:
  clintox_path:
  sider_path: