model_name: "PredictorBA"
project_filepath: "/raid/KAICD_sarscov2/"
save_filepath: "Predictor/checkpoint/"
smiles_language_filepath: "Config/PredictorBA_smiles_language.pkl"
protein_language_filepath: "Config/PredictorBA_protein_language.pkl"
params_filepath: "Config/PredictorBA.json"
train_affinity_filepath: "data/pretraining/Predictor/filtered_train_binding_data.csv"
test_affinity_filepath: "data/pretraining/Predictor/filtered_val_binding_data.csv"
protein_filepath: "data/pretraining/Predictor/sequences.smi"
smi_filepath: "data/pretraining/Predictor/filtered_ligands.smi"