project_filepath: "/raid/PaccMann_sarscov2/"
save_filepath: "paccmann_predictor/checkpoint/"
smiles_language_filepath: "data/pretraining/language_models/smiles_language_chembl_gdsc_ccle_tox21_zinc_organdb_bindingdb.pkl"
protein_language_filepath: "data/pretraining/language_models/protein_language_bindingdb.pkl"
params_filepath: "Config/Predictor.json"
train_affinity_filepath: "data/pretraining/affinity_predictor/filtered_train_binding_data.csv"
test_affinity_filepath: "data/pretraining/affinity_predictor/filtered_val_binding_data.csv"
protein_filepath: "data/pretraining/affinity_predictor/sequences.smi"
smi_filepath: "data/pretraining/affinity_predictor/filtered_ligands.smi"