model_name: "PredictorDS"
project_filepath: "/raid/KAICD_sarscov2/"
save_filepath: "Predictor/checkpoint/"
smiles_language_filepath: "Config/PredictorDS_smiles_language.pkl"
params_filepath: "Config/PredictorDS.json"
train_sensitivity_filepath: "data/pretraining/Predictor/ccle_ic50_train_fraction_0.9_id_246_seed_42.csv"
test_sensitivity_filepath: "data/pretraining/Predictor/ccle_ic50_test_fraction_0.1_id_246_seed_42.csv"
train_dataset_filepath: "preprocessing/PredictorDS_train_dataset.pkl"
test_dataset_filepath: "preprocessing/PredictorDS_test_dataset.pkl"
gep_filepath: "data/pretraining/Predictor/ccle-rnaseq_gene-expression.csv"
smi_filepath: "data/pretraining/Predictor/ccle.smi"
gene_filepath: "Config/PredictorDS_gene.pkl"