model_name: "ProtVAE"
project_filepath: "/raid/KAICD_sarscov2/"
save_filepath: "ProtVAE/checkpoint/"
params_filepath: "Config/ProtVAE.json"
train_protein_filepath: "data/pretraining/ProtVAE/tape_encoded/train_representation.csv"
test_protein_filepath: "data/pretraining/ProtVAE/tape_encoded/val_representation.csv"
train_dataset_filepath: "preprocessing/protVAE_train_dataset.pkl"
test_dataset_filepath: "preprocessing/protVAE_test_dataset.pkl"