project_filepath: "./"
mol_model_path: "ChemVAE/checkpoint/ChemVAE_5M_antiviral.ckpt"
protein_model_path: "ProtVAE/checkpoint/ProtVAE.ckpt"
affinity_model_path: "Predictor/checkpoint/Predictor.ckpt"
protein_data_path: "/raid/KAICD_sarscov2/data/training/merged_sequence_encoding/uniprot_covid-19.csv"
params_path: "Config/Reinforce.json"
model_name: "pKAICD_sarscov2"
test_protein_id: "23"
unbiased_predictions_path: "/raid/KAICD_sarscov2/data/training/unbiased_predictions"
tox21_path: "Toxicity/checkpoint/Toxicity.ckpt"
organdb_path:
site:
clintox_path:
sider_path: