project_filepath: "/raid/KAICD_sarscov2/"
chem_model_path: "ChemVAE/checkpoint/ChemVAE_5M_antiviral_2.ckpt"
prot_model_path: "ProtVAE/checkpoint/ProtVAE.ckpt"
pred_model_path: "Predictor/checkpoint/Predictor.ckpt"
protein_data_path: "data/training/merged_sequence_encoding/uniprot_covid-19.csv"
params_path: "Config/Reinforce.json"
chem_model_params_path: "Config/ChemVAE.json"
prot_model_params_path: "Config/ProtVAE.json"
pred_model_params_path: "Config/PredictorBA.json"
chem_smiles_language_path: "Config/ChemVAE_selfies_language.pkl"
pred_smiles_language_path: "Config/PredictorBA_smiles_language.pkl"
pred_protein_language_path: "Config/PredictorBA_protein_language.pkl"
model_name: "KAICD_RL_ANTIVIRAL"
test_protein_id: "40"
unbiased_predictions_path: "data/training/unbiased_predictions"
tox21_path: "Toxicity/checkpoint/Toxicity.ckpt"
organdb_path:
site:
clintox_path:
sider_path: