model_name: "Toxicity"
project_filepath: "/raid/KAICD_sarscov2/"
save_filepath: "Toxicity/checkpoint/"
params_filepath: "Config/Toxicity.json"
embedding_path: "data/pretraining/Toxicity/smiles_vae_embeddings.pkl"
train_score_filepath: "data/pretraining/Toxicity/tox21_train.csv"
test_score_filepath: "data/pretraining/Toxicity/tox21_test.csv"
smi_filepath: "data/pretraining/Toxicity/tox21.smi"
smiles_language_filepath: "data/pretraining/language_models/smiles_language_tox21.pkl"