project_filepath: "/raid/PaccMann_sarscov2/"
save_filepath: "paccmann_toxsmi/checkpoint/"
params_filepath: "Config/Toxicity.json"
embedding_path: "data/pretraining/toxicity_predictor/smiles_vae_embeddings.pkl"
train_score_filepath: "data/pretraining/toxicity_predictor/tox21_train.csv"
test_score_filepath: "data/pretraining/toxicity_predictor/tox21_test.csv"
smi_filepath: "data/pretraining/toxicity_predictor/tox21.smi"
smiles_language_filepath: "data/pretraining/language_models/smiles_language_tox21.pkl"